### PR TITLE
feat(blog): add dmn-js@8.3 blog post

### PR DESCRIPTION
**Pull request by philippfromme**

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Very like it, especially the "Encouraging Best Practices... without enforcing them" structure, very cool 👏

**Comment by barmac** [comment]
LGTM 🚀

**Comment by nikku** [comment]
Everyone likes it, no one approves :+1:

**Comment by nikku** [comment]
Added a few minor changes on top, cf. https://github.com/bpmn-io/bpmn.io/commit/04d8e930331efd3c5ecca794e925e489c848ea99.

TLDR:

* call to action! Link to demo!
* not so generic title
* DMN diagram -> DRD (this is what the thing is called)

:clap:

**Comment by nikku** [comment]
Also updated the example diagram we host on demo.bpmn.io:

image

It is now TOP_DOWN layouted.

**Comment by philippfromme** [comment]
@nikku Nice! Thank you! 😄

**Pull request merged**
