### PR TITLE
chore: simplify CamundaCon banner

### PR DESCRIPTION
**Pull request by philippfromme**
image

### CODE REVIEW

**Comment by philippfromme** [comment]
Since the script runs once the DOM content has finished loading, there's a little bit of a flicker. Not sure if we can do anything to prevent this.

**Comment by nikku** [comment]
Added some changes via https://github.com/bpmn-io/bpmn.io/pull/164/commits/3670a65c1639bc08a3b58b72815c4ff0f43b0bd1.

Now it is mobile friendly, and should be shown on every page :blush:.

**Comment by nikku** [comment]
Great stuff!

**Comment by nikku** [comment]
Closes https://github.com/bpmn-io/internal-docs/issues/823.

**Pull request merged**
