### PR TITLE
Bubblz blog post ✏️

### PR DESCRIPTION
**Pull request by mzane42**
Hi Nico,
Hope you will like this blog post :)

### CODE REVIEW

**Comment by nikku** [comment]
Sorry for the delay on my side to review this PR. I'll have a look today :slightly_smiling_face:.

**Comment by mzane42** [comment]
Hello @nikku Thanks for your nice review, i just check it out, do you want me to add something else ?
Have a nice day !

**Review by nikku — COMMENTED** [review]
Great post! 

I've added some necessary structures around it (intro, thank you, about the author) and tried to improve the messaging in a few places: https://github.com/bpmn-io/bpmn.io/pull/104/commits/ac455711887d2b0d4cd72c1e4c4bf59e807d4e17.

Please have another look and give your :+1:.

You can see the post live like this:

```
npm install
npm run dev

## GOTO http://localhost:9012/blog/posts/2021-bpmn-js-visual-workflow-configuration-in-bubblz.html
```

If you want to you can add Sebastien as an author, too, or change your description :slightly_smiling_face:.

Thanks again so much for contributing this post and sharing your bpmn-js story.

**Comment by nikku** [comment]
@mzane42 Read above :arrow_up:.

Please double check the changes and consider to change your author description at the end of the post.
Also, consider adding Sebastien as an author, if you want to.

**Comment by mzane42** [comment]
Hi @nikku,
I just double check with the team, and they like it.
Thanks for your help ! (Sebastien doesn't have github)

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
KUDOs to the team. Thanks again!

**Pull request merged**
