### PR TITLE
feat(blog): add form-js v0.6.0 blog post

### PR DESCRIPTION
**Pull request by philippfromme**
Closes https://github.com/bpmn-io/bpmn.io/issues/113
Related to https://github.com/bpmn-io/form-js/issues/216

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for the post.

I've updated it with an improved title and social meta-data. I also changed it slightly (swapping both sections) and linked the demo.

Please have a read.

**Comment by philippfromme** [comment]
Looking good! 💅🏻 Shall we merge?

**Comment by nikku** [comment]
Wanted to give you the chance to see what I followed up with.

Yea, let us merge and publish :tada:

**Comment by philippfromme** [comment]
@nikku Thanks, mate! Good stuff! 🚀

**Pull request merged**
